### ISSUE TITLE
Bug while trying to set inputs on ESWC replay

### ISSUE THREAD

**Issue by TheLevelCode** [bigbang1112-cz/clip-input#8]
So I was going to generate some inputs to my epic D-0 edgebug, but when I opened the Clip Input I encountered this error while generating the inputs:
![image](https://user-images.githubusercontent.com/63305091/144693122-c4bf01bb-2f28-4d0f-9803-b941a8b53185.png)
I have tried to change the file location to something else but it still gives that error, am I missing something to fix this or is this a common issue that will not be fixed?
Btw my Clip Input version is the latest, aka 1.2.0-rc x64-Bit

**Comment by BigBang1112** [comment]
Oops, forgot to include the case in the "input wrapping" when the inputs are not available. Should be fixed (5ca8abf2a703dd635a5ecba3f6768cf896ac044b) and included on full release sometime.
Simply said, this error currently happens when there are no inputs available in the GBX file.

**Comment by BigBang1112** [comment]
Because of my recent statement of not updating any executables (due to the recent rise of exe scams on Discord), I am not going to create a new executable release manually, until I manage to make a builder through GitHub Actions working. Clip Input 1.2.0 is considered finished and there won't be any further updates and the repository will be archived after the automated release. The future will lead to Clip Input 2 in a browser.

This issue will be closed after the 1.2.0 release.

**Comment by BigBang1112** [comment]
This issue is being closed due to 2.0 release lol
